import type { AccountingOutput } from "./finance.contracts";

export type FinanceDocumentLine = {
	label: string;
	value: string;
};

export type FinanceDocumentTableLine = {
	description: string;
	quantity: number;
	unitAmount: string;
	discount: string;
	total: string;
};

export type FinanceDocumentPdfInput = {
	type: "Quote" | "Invoice";
	number: string;
	title: string;
	customer: string;
	event: string;
	service: string;
	currency: string;
	lines: FinanceDocumentTableLine[];
	totals: FinanceDocumentLine[];
	terms: string | null;
	meta: FinanceDocumentLine[];
	audit: AccountingOutput["entries"];
};

export function renderFinanceDocumentPdf(
	input: FinanceDocumentPdfInput,
): Buffer {
	const commands: string[] = [
		"0.92 0.95 0.98 rg 0 760 595 82 re f",
		text(input.type, 48, 790, 24, true),
		text(input.number, 48, 760, 12, false),
		text("Event Props", 430, 790, 18, true),
		text("Finance document", 430, 770, 10, false),
		text(input.title, 48, 725, 16, true),
		text(`Customer: ${input.customer}`, 48, 700, 10, false),
		text(`Event: ${input.event}`, 48, 684, 10, false),
		text(`Service: ${input.service}`, 48, 668, 10, false),
	];

	let y = 634;
	commands.push(
		text("Description", 48, y, 9, true),
		text("Qty", 310, y, 9, true),
		text("Unit", 355, y, 9, true),
		text("Discount", 425, y, 9, true),
		text("Total", 505, y, 9, true),
		"0.8 0.84 0.9 RG 48 626 500 1 re S",
	);
	y -= 22;

	for (const line of input.lines.slice(0, 14)) {
		commands.push(
			text(line.description, 48, y, 9, false),
			text(String(line.quantity), 314, y, 9, false),
			text(line.unitAmount, 355, y, 9, false),
			text(line.discount, 425, y, 9, false),
			text(line.total, 505, y, 9, false),
		);
		y -= 18;
	}

	y -= 10;
	for (const total of input.totals) {
		commands.push(
			text(total.label, 360, y, 9, false),
			text(total.value, 485, y, 9, true),
		);
		y -= 16;
	}

	y -= 12;
	commands.push(text("Details", 48, y, 11, true));
	y -= 18;
	for (const item of input.meta) {
		commands.push(text(`${item.label}: ${item.value}`, 48, y, 9, false));
		y -= 15;
	}

	if (input.terms) {
		y -= 12;
		commands.push(text("Terms", 48, y, 11, true));
		y -= 18;
		for (const line of wrap(input.terms, 82).slice(0, 6)) {
			commands.push(text(line, 48, y, 9, false));
			y -= 14;
		}
	}

	if (input.audit.length > 0) {
		y -= 10;
		commands.push(text("Ledger evidence", 48, y, 11, true));
		y -= 18;
		for (const entry of input.audit.slice(0, 5)) {
			const amount =
				entry.debitCents > 0
					? `Debit ${money(entry.debitCents, entry.currency)}`
					: `Credit ${money(entry.creditCents, entry.currency)}`;
			commands.push(
				text(
					`${entry.occurredAt} ${entry.account.name} ${amount}`,
					48,
					y,
					8,
					false,
				),
			);
			y -= 13;
		}
	}

	commands.push(text("Generated by Comp AI Finance OS", 48, 42, 8, false));
	return buildPdf(commands.join("\n"));
}

export function money(cents: number, currency: string): string {
	return `${currency} ${(cents / 100).toFixed(2)}`;
}

function buildPdf(content: string): Buffer {
	const stream = Buffer.from(content, "utf8");
	const objects = [
		"<< /Type /Catalog /Pages 2 0 R >>",
		"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
		`<< /Length ${stream.byteLength} >>\nstream\n${content}\nendstream`,
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
	];
	const chunks = ["%PDF-1.4\n"];
	const offsets = [0];
	for (const [index, object] of objects.entries()) {
		offsets.push(Buffer.byteLength(chunks.join(""), "utf8"));
		chunks.push(`${index + 1} 0 obj\n${object}\nendobj\n`);
	}
	const xref = Buffer.byteLength(chunks.join(""), "utf8");
	chunks.push(`xref\n0 ${objects.length + 1}\n`);
	chunks.push("0000000000 65535 f \n");
	for (const offset of offsets.slice(1)) {
		chunks.push(`${String(offset).padStart(10, "0")} 00000 n \n`);
	}
	chunks.push(
		`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`,
	);
	return Buffer.from(chunks.join(""), "utf8");
}

function text(
	value: string,
	x: number,
	y: number,
	size: number,
	bold: boolean,
): string {
	return `BT /${bold ? "F2" : "F1"} ${size} Tf ${x} ${y} Td (${escapePdfText(
		value,
	)}) Tj ET`;
}

function escapePdfText(value: string): string {
	return value
		.replaceAll("\\", "\\\\")
		.replaceAll("(", "\\(")
		.replaceAll(")", "\\)")
		.replaceAll("\r", " ")
		.replaceAll("\n", " ");
}

function wrap(value: string, size: number): string[] {
	const words = value.split(/\s+/).filter(Boolean);
	const lines: string[] = [];
	let current = "";
	for (const word of words) {
		const next = current ? `${current} ${word}` : word;
		if (next.length > size) {
			if (current) lines.push(current);
			current = word;
		} else {
			current = next;
		}
	}
	if (current) lines.push(current);
	return lines;
}
